# Generated by Django 5.2.14 on 2026-05-09 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('recent_posts', 'Recent posts'), ('featured_post', 'Featured post'), ('newsletter', 'Newsletter'), ('text', 'Text'), ('cta', 'Call to action')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_blocks', to='madga.site')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['site', 'sort_order'], name='madga_homep_site_id_04b252_idx')],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Relative path (e.g. /blog/) or absolute URL.', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='madga.navitem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='madga.site')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['site', 'parent', 'sort_order'], name='madga_navit_site_id_2715f3_idx')],
            },
        ),
    ]
