# Generated by Django 5.2.14 on 2026-05-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0004_page_featured_image_page_og_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='navitem',
            name='madga_navit_site_id_2715f3_idx',
        ),
        migrations.AddField(
            model_name='navitem',
            name='location',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=20),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url',
            field=models.CharField(blank=True, help_text='Relative path (e.g. /blog/), absolute URL, or empty for footer column titles.', max_length=500),
        ),
        migrations.AddIndex(
            model_name='navitem',
            index=models.Index(fields=['site', 'location', 'parent', 'sort_order'], name='madga_navit_site_id_03902c_idx'),
        ),
    ]
