# Generated by Django 5.2.14 on 2026-05-16 15:55

import django.db.models.deletion
import madga.models.api_keys
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0005_remove_navitem_madga_navit_site_id_2715f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Human-readable name for this key (e.g. 'iOS app').", max_length=80)),
                ('key', models.CharField(default=madga.models.api_keys._new_key, max_length=64, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text="Pin this key to a specific site. NULL = derive from user's first SiteUser.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_api_keys', to='madga.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madga_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='madga_usera_key_632b65_idx')],
            },
        ),
    ]
