# Generated by Django 5.2.14 on 2026-05-16 21:04

import django.db.models.deletion
import madga.models.broadcast
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0007_alter_page_status_alter_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher_key', models.CharField(help_text='Key of a registered Publisher (e.g. email_subscribers, linkedin).', max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('related_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="If set in the future, the worker won't pick the job up before this time.", null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('targets_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madga_broadcasts_created', to=settings.AUTH_USER_MODEL)),
                ('related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='madga.page')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='madga.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='madga.site')),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='madga_broad_site_id_599eee_idx'), models.Index(fields=['status', 'scheduled_at'], name='madga_broad_status_07af5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(choices=[('signup', 'Signup'), ('manual', 'Manual'), ('imported', 'Imported'), ('form', 'Form')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Set when the user confirms double opt-in. Empty means single opt-in.', null=True)),
                ('unsubscribe_token', models.CharField(default=madga.models.broadcast._new_unsubscribe_token, max_length=64, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='madga.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madga_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
                'unique_together': {('site', 'email')},
            },
        ),
    ]
