# Generated by Django 5.2.14 on 2026-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0008_broadcastjob_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='variants',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20),
        ),
    ]
