# Generated by Django 5.2.14 on 2026-05-16 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0009_mediafile_variants_alter_mediafile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher_key', models.CharField(help_text="Key of a registered Publisher (e.g. 'twitter', 'linkedin').", max_length=50)),
                ('handle', models.CharField(blank=True, help_text="Public handle/username shown in the studio (e.g. '@aitorruiz').", max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('audience_size', models.PositiveIntegerField(default=0, help_text='Cached follower/subscriber count for display.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('_credentials_enc', models.TextField(blank=True, db_column='credentials_enc')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='madga.site')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['publisher_key', 'handle'],
                'unique_together': {('site', 'publisher_key', 'handle')},
            },
        ),
    ]
