# Generated by Django 5.2.14 on 2026-05-17 07:21

import django.db.models.deletion
import madga.models.webhooks
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0010_publisheraccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastjob',
            name='status',
            field=models.CharField(choices=[('queued_on_publish', 'Queued on publish'), ('pending', 'Pending'), ('running', 'Running'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="Human-readable label, shown in the studio (e.g. 'aplica.do jobs sync').", max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(blank=True, default=list, help_text='List of event keys this endpoint subscribes to. Empty = all events.')),
                ('secret', models.CharField(default=madga.models.webhooks._new_webhook_secret, help_text='Used to compute the X-Madga-Signature header on every delivery.', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madga_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='madga.site')),
            ],
            options={
                'verbose_name': 'Webhook endpoint',
                'verbose_name_plural': 'Webhook endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retry', 'Retry scheduled'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='madga.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook delivery',
                'verbose_name_plural': 'Webhook deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='madga_webho_status_a168da_idx')],
            },
        ),
    ]
