# Generated by Django 5.2.14 on 2026-05-17 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0011_webhooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('form_key', models.CharField(blank=True, help_text="Short identifier the host project picks ('contact', 'apply', …)", max_length=80)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='madga.site')),
            ],
            options={
                'verbose_name': 'Form submission',
                'verbose_name_plural': 'Form submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
