# Generated by Django 5.2.14 on 2026-05-17 07:38
#
# AlterField from UUID → PositiveInteger doesn't work on Postgres (no
# automatic cast). FormSubmission only landed in 0012 (same release),
# so nothing in production has UUID values yet — safest is to drop
# then re-add the column. RunSQL uses IF EXISTS so it's idempotent
# on sqlite databases that already ran the original AlterField.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0012_formsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='block_id',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='block_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
