# Generated by Django 5.2.14 on 2026-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0012_formsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='block_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
