# Generated by Django 5.2.14 on 2026-05-17 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madga', '0013_alter_formsubmission_block_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOAuthApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher_key', models.CharField(help_text="Publisher this override applies to (e.g. 'twitter', 'instagram').", max_length=50)),
                ('client_id', models.CharField(max_length=200)),
                ('_client_secret_enc', models.TextField(blank=True, db_column='client_secret_enc', help_text='Fernet ciphertext of the secret.')),
                ('notes', models.CharField(blank=True, help_text="Internal note — shown on the Channels page (e.g. 'Acme corporate app').", max_length=300)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_apps', to='madga.site')),
            ],
            options={
                'verbose_name': 'Site OAuth app',
                'verbose_name_plural': 'Site OAuth apps',
                'ordering': ['publisher_key'],
                'unique_together': {('site', 'publisher_key')},
            },
        ),
    ]
